plugin 'cocoapods-fix-react-native'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# use_frameworks!

target 'ChainReactApp2018' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ChainReactApp2018
  # Flexbox Layout Manager Used By React Natve
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # React Native
  pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTTest',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS',
    'fishhook'
  ]

  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  # Replace bad code in React Native libs
  # https://gist.github.com/Jpunt/3fe75effd54a702034b75ff697e47578
  def change_lines_in_file(file_path, &change)
    print "Fixing #{file_path}...\n"

    contents = []

    file = File.open(file_path, 'r')
    file.each_line do | line |
      contents << line
    end
    file.close

    File.open(file_path, 'w') do |f|
      f.puts(change.call(contents))
    end
  end

  #https://medium.com/@mspoonam/integrating-react-native-into-ios-native-project-322ddd39792c
  change_lines_in_file('../node_modules/react-native/Libraries/WebSocket/RCTReconnectingWebSocket.m') do |lines|
    lines.map { |line| line.include?("#import <fishhook/fishhook.h>") ? '#import <React/fishhook.h>' : line }
  end

end
